In [148]:
import numpy as np

In [149]:
#Create a NumPy array with numbers from 1 to 10.
arr1=np.array([1,2,3,4,5,6,7,8,9,10])

In [150]:
#Print shape of an array.
arr1.shape

(10,)

In [151]:
#Print datatype of array elements.
arr1.dtype

dtype('int64')

In [152]:
#Create array of zeros.
arr2=np.zeros(4)
arr2

array([0., 0., 0., 0.])

In [153]:
#Create array of ones.
arr3=np.ones(4)
arr3

array([1., 1., 1., 1.])

In [154]:
#Create identity matrix.
ide=np.identity(3)
iden=np.eye(4)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [155]:
#Create array using arange().
arr=np.arange(4)
arr.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [156]:
#Create array using linspace().
arr=np.linspace(1,20,9,dtype=int)
arr

array([ 1,  3,  5,  8, 10, 12, 15, 17, 20])

In [199]:
#Reshape a 1D array into 2D array.
a=arr.reshape(3,3)
a.shape
a

array([[ 1,  3,  5],
       [ 8, 10, 12],
       [15, 17, 20]])

In [158]:
#Flatten a 2D array into 1D array.
a.flatten()

array([ 1,  3,  5,  8, 10, 12, 15, 17, 20])

In [159]:
#Find sum of all array elements.
sum=0
for i in arr:
    sum+=i
print(f"sum: {sum}")

sum: 91


In [160]:
#Find mean of array.
arr.mean()

np.float64(10.11111111111111)

In [161]:
#Find maximum and minimum value in array.
print(arr.max())
print(arr.min())


20
1


In [162]:
#Find index of maximum element.
print(arr.argmax())

8


In [163]:
brr=np.linspace(10,40,9,dtype=int)

In [164]:
#Add two arrays.
b=brr.reshape(3,3)
print(a+b)

[[11 16 22]
 [29 35 40]
 [47 53 60]]


In [165]:
#Subtract two arrays.
print(b-a)

[[ 9 10 12]
 [13 15 16]
 [17 19 20]]


In [166]:
#Multiply two arrays.
print(a*b)

[[ 10  39  85]
 [168 250 336]
 [480 612 800]]


In [167]:
#Divide two arrays.
print(a/b)

[[0.1        0.23076923 0.29411765]
 [0.38095238 0.4        0.42857143]
 [0.46875    0.47222222 0.5       ]]


In [168]:
#Find square of each element in array.
print(a**2)

[[  1   9  25]
 [ 64 100 144]
 [225 289 400]]


In [169]:
#Find cube of each element in array.
print(a**3)

[[   1   27  125]
 [ 512 1000 1728]
 [3375 4913 8000]]


In [178]:
#Sort an array.
a.sort(axis=1)
arr.sort()
arr

array([ 1,  3,  5,  8, 10, 12, 15, 17, 20])

In [179]:
#Reverse an array.
arr[::-1]

array([20, 17, 15, 12, 10,  8,  5,  3,  1])

In [187]:
#Count even numbers in array.
count=0
for i in arr:
    if i%2==0:
        count+=1
        print(i,end=" ")
print("\n",count)

8 10 12 20 
 4


In [188]:
#Count odd numbers in array.
count=0
for i in arr:
    if i%2!=0:
        count+=1
        print(i,end=" ")
print("\n",count)

1 3 5 15 17 
 5


In [ ]:
#Find all elements greater than 10.
count=0
for i in arr:
    if i>=10:
        count+=1
        print(i,end=" ")
print("\n",count)

10 12 15 17 20 
 5


In [191]:
#Slice first 5 elements of array.
arr[:5]

array([ 1,  3,  5,  8, 10])

In [196]:
#Slice last 3 elements of array.
arr[-3:]

array([15, 17, 20])

In [ ]:
#Access element from 2D array using index.
a[2][2]
#a[Rows][cols]

np.int64(20)

In [210]:
#Find transpose of matrix.
a.T

array([[ 1,  8, 15],
       [ 3, 10, 17],
       [ 5, 12, 20]])

In [211]:
#Multiply two matrices.
print(a*b)

[[ 10  39  85]
 [168 250 336]
 [480 612 800]]


In [214]:
#Find determinant of matrix.
print(np.linalg.det(a))
print(np.linalg.det(b))


-13.999999999999996
-99.99999999999996


In [216]:
#Find inverse of matrix.
print(np.linalg.inv(a))
print(np.linalg.inv(b))

[[ 0.28571429 -1.78571429  1.        ]
 [-1.42857143  3.92857143 -2.        ]
 [ 1.         -2.          1.        ]]
[[ 0.08 -0.92  0.61]
 [-0.56  1.44 -0.77]
 [ 0.44 -0.56  0.23]]


In [224]:
#Generate random integers array.
new_ar=np.random.randint(5,20,5)
print(new_ar)

[13 18  5  5  9]


In [234]:
#Generate random float numbers.
new_arr=np.random.randn(20)
print(new_arr)

[-1.26499839  2.57205558 -0.3655115   0.79587016  0.05856221  0.39449504
 -1.71581758  0.45284064  1.30698967  1.06891124  1.7441127   2.23087126
 -0.60988664  0.84490488 -0.42054712  0.65038153  2.7378048   2.04130257
 -0.33521265 -1.10709217]


In [238]:
#Find unique elements in array.
m=np.array([1,2,3,1,3,4,2,4,5])
print(np.unique(m))

[1 2 3 4 5]


In [247]:
#Merge two arrays.
n=np.concatenate((arr,m))
s1=np.vstack((a,b))
s2=np.hstack((a,b))
print(f"1D array merged: \n {n} \n 2D vertical array merged: \n {s1} \n 2D horizantal array merged: \n {s2}")

1D array merged: 
 [ 1  3  5  8 10 12 15 17 20  1  2  3  1  3  4  2  4  5] 
 2D vertical array merged: 
 [[ 1  3  5]
 [ 8 10 12]
 [15 17 20]
 [10 13 17]
 [21 25 28]
 [32 36 40]] 
 2D horizantal array merged: 
 [[ 1  3  5 10 13 17]
 [ 8 10 12 21 25 28]
 [15 17 20 32 36 40]]


In [256]:
#Split array into multiple parts.
s=np.split(s2,3)
print(s[0])

[[ 1  3  5 10 13 17]]


In [258]:
#Replace negative values with zero.
new_arr[new_arr<0]=0
new_arr

array([0.        , 2.57205558, 0.        , 0.79587016, 0.05856221,
       0.39449504, 0.        , 0.45284064, 1.30698967, 1.06891124,
       1.7441127 , 2.23087126, 0.        , 0.84490488, 0.        ,
       0.65038153, 2.7378048 , 2.04130257, 0.        , 0.        ])

In [275]:
#Count frequency of elements in array.
count=0
for i in arr:
    if i==1:
        count+=1
print("\n",count)
def fr(r):
    for i in range(len(a)):
        for j in range(len(a)):
            if a[i][j]==r:
                print(f"Found at index : a[ {i} ][{j}]")
d=10
fr(d)


 1
Found at index : a[ 1 ][1]


In [280]:
#Find standard deviation and variance of array.
print("Standard deviation for arr: ",arr.std())#1D array
print("Standard deviation: ",b.std())#2D array
print("Varriance:",arr.var())
print(b.var())




Standard deviation for arr:  6.118177732416091
Standard deviation:  9.72967967955095
Varriance: 37.4320987654321
94.66666666666667
